services:
  lessurl:
    build:
      context: .
      target: production
      dockerfile: dockerfile
    restart: 'always'
    container_name: lessurl
    env_file: .env
    ports:
      - 3000:3000
